on:
  issues:
    types: [opened]


jobs:
  create_task:
    runs-on: ubuntu-latest
    name: Create a Todois task
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: log Issue data
        run: echo ${{github.issue.title}}
      - name: Create Todoist Step
        uses: ./ # Uses an action in the root directory
        id: todoist
        with:
          task-content: 'Test from workfrom'
          token: ${{ secrets.TODOIST_API_KEY }}
